name: Repository Dispatch

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "Enter name"
        required: true
        default: 'jayshree'
      
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          #repository: GuillaumeFalourd/useful-actions
          repository: jassu2017/github-actions-test20
          event-type: event-demo
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
